<a href="https://colab.research.google.com/github/johnlaraji1608-collab/passenger_logisticregression/blob/main/passenger_logisticregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/gender_submission.csv')

In [ ]:
df['Embarked'] = np.random.choice(['S', 'C', 'Q'], size=len(df), p=[0.7, 0.2, 0.1])
df['Sex'] = np.random.choice(['male', 'female'], size=len(df), p=[0.6, 0.4])

In [ ]:
df.head()

   PassengerId  Survived Embarked     Sex
0          892         0        C  female
1          893         1        C  female
2          894         0        C  female
3          895         0        S  female
4          896         1        S  female

In [ ]:
df.shape

(418, 2)

In [ ]:
df.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB

In [ ]:
ports = pd.get_dummies(df.Embarked , prefix='Embarked')
ports.head()

   Embarked_C  Embarked_Q  Embarked_S
0        True       False       False
1        True       False       False
2        True       False       False
3       False       False        True
4       False       False        True

In [ ]:
df=df.join(ports)
df.drop(['Embarked'], axis=1, inplace=True)

In [ ]:
df.head()

   PassengerId  Survived  Embarked_C  Embarked_Q  Embarked_S
0          892         0        True       False       False
1          893         1        True       False       False
2          894         0       False       False        True
3          895         0       False       False        True
4          896         1       False       False        True

In [ ]:
df.Sex = df.Sex.map({'male':0, 'female':1})

In [ ]:
df.head()

   PassengerId  Survived Embarked  Sex
0          892         0        S    0
1          893         1        S    0
2          894         0        S    0
3          895         0        S    1
4          896         1        S    1